name: Node.js CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      if: always()
      run: npm run lint

    - name: Run Prettier
      if: always()
      run: npm run prettier --write

    - name: Run Jest tests
      if: always()
      run: CI=true npm run test

    - name: Build the application
      run: npm run build
