name: Node.js CI

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: ./codebase/rdicidr-0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 15.5.1
        uses: actions/setup-node@v4
        with:
          node-version: 15.5.1
          cache: "npm"

      - run: npm install
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run lint
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run prettier
        working-directory: ./codebase/rdicidr-0.1.0
      - run: CI=true npm run test
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run build 
        working-directory: ./codebase/rdicidr-0.1.0
